### ISSUE TITLE
请问贵组最近是去避风了吗？

### ISSUE THREAD

**Issue by blip-glitch** [vcb-s/vcb-s.github.io#1]
先是主站显示要维护，再是论坛和主站都无法访问，微信号也已注销，网上也没有关于这件事的任何消息。如果是避风头的话应该在脸肿被抓后就关闭网站或者像御所一样设置结界，可是就在御所已经开放后才关闭网站，，，，，，，，这是已经出事了吗？？？好担心。。。。。。

**Comment by IOAOl** [comment]
我想应该没事，bt还在正常更新

**Comment by chirophy** [comment]
我也想问，感觉失去了一大支柱
