### ISSUE TITLE
在vcb-s.com上注册账号时无法收到验证码邮件

### ISSUE THREAD

**Issue by DarthMikuH** [vcb-s/vcb-s.github.io#2]
在vcb-s.com上注册账号时无法收到验证码邮件
以尝试过gmail和qq,多次不同时间尝试均失败...
由于无法找到其他与贵组的联系方式,不得不在这里发个issue...
还望谅解

**Comment by Inori-Lover** [comment]
经检查国内常见的数家邮箱均可正常收取测试邮件。

建议检查邮箱垃圾邮件文件夹或收件软件是否带特殊删除规则。
